backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    files:
      - label: "Events List"
        name: "events"
        file: "content/events.json"
        fields:
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "members"
    label: "Members"
    files:
      - label: "Members List"
        name: "members"
        file: "content/members.json"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }

  - name: "gallery"
    label: "Gallery"
    files:
      - label: "Gallery List"
        name: "gallery"
        file: "content/gallery.json"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "url", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string" }
